# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24b40f65472c697f311400da79b0d0aa7ee7992e2121a5eb446924a91205fd7814dfd4efbb1b5162bbc0df8394b575383b00ccc2150112f96db35ded908e519c

test:
  secret_key_base: cf4067583cd0e6cf9faac27932aa7dd809971bb793bacb52311dedb104748a9c1f3b95a69d929808dcd3056dc0192607f3e481ccc0269d3461a43e9fe2f12183

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
